[package]
name = "coolers"
version = "0.1.0"
edition = "2018"

[lib]
name = "coolers"
path = "src/lib.rs"

[[bin]]
name = "clrs"
path = "src/main.rs"

[dependencies]
clap = {version = "3.1.2", features = ["derive"]}
